final List<Map<String, dynamic>> shippingData = [
  {
    'id': 'JK126K532',
    'status': 'In Delivery',
    'trackingNumber': '34589762',
    'date': '13 Jul. 2024',
    'location': 'Alido',
    'from': '13 Jul. 2024',
    'to': '13 Jul. 2024',
    'customerName': 'Alice',
    'steps': [
      {'title': 'Moving from', 'subtitle': 'June 10, 2018 10:45pm'},
      {'title': 'In transit', 'subtitle': 'Jackline Tower, New York'},
      {'title': 'Out for delivery', 'subtitle': 'Tracking Number'},
      {'title': 'Delivery', 'subtitle': 'Not delivered yet'},
    ],
  },
  {
    'id': 'JK126K534',
    'status': 'Complete',
    'trackingNumber': '98765432',
    'date': '11 Jul. 2024',
    'location': 'Dubai',
    'from': '10 Jul. 2024',
    'to': '11 Jul. 2024',
    'customerName': 'Alice',
    'steps': [
      {'title': 'Moving from', 'subtitle': 'July 9, 2024 2:00pm'},
      {'title': 'In transit', 'subtitle': 'Logistics Hub, Dubai'},
      {'title': 'Out for delivery', 'subtitle': 'Track ID: 9876'},
      {'title': 'Delivery', 'subtitle': 'Delivered successfully'},
    ],
  },
  {
    'id': 'JK126K533',
    'status': 'Complete',
    'trackingNumber': '98765432',
    'date': '11 Jul. 2024',
    'location': 'Dubai',
    'from': '10 Jul. 2024',
    'to': '11 Jul. 2024',
    'customerName': 'Alice',
    'steps': [
      {'title': 'Moving from', 'subtitle': 'July 9, 2024 2:00pm'},
      {'title': 'In transit', 'subtitle': 'Logistics Hub, Dubai'},
      {'title': 'Out for delivery', 'subtitle': 'Track ID: 9876'},
      {'title': 'Delivery', 'subtitle': 'Delivered successfully'},
    ],
  },
];
